#!/bin/bash

msg "Setting up aliases..."

alias ll='ls --color=auto -hal'
alias mkdir='mkdir -pv'
alias md='mkdir'
alias show='open'
alias dev='code'
alias tl='tree -a -C -L 2'
alias dsrc='docker ps -q | xargs -r docker stop'

alias fun="random-chuck-fact"

alias lntfix='yarn lint --fix'
alias lnt='yarn lint'
alias tst='yarn test'

alias gpt='git push --follow-tags'

# alias goto-sp = 'cdws some-project'
alias q='exit'

successmsg "Aliases done. ${CHECK}"
