#!/bin/bash

msg "Exporting global environment variables..."

export CLICOLOR=1

export GH_REGISTRY_TOKEN=
export GH_REGISTRY_USERNAME=

export JAVA_HOME="$(jrunscript -e 'java.lang.System.out.println(java.lang.System.getProperty("java.home"));')"
#export JAVA_INCLUDE_PATH="/opt/homebrew/opt/openjdk/include"
# To be used as follows
#export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"

# export M2_HOME=/opt/maven
# export MAVEN_HOME=/opt/maven
MC_CURRENT_OS="$(uname -s)"
export MC_CURRENT_OS

export MC_WORKSPACE_PATH="$HOME/ws"

export CHECK="\xE2\x9C\x94"
export CROSS="\xE2\x9D\x8C\x0A"

successmsg "Exports done. ${CHECK}"
