#!/bin/bash

msg "Setting up general functions..."

function cdws {
    cd "$MC_WORKSPACE_PATH/$1" || { echo "Directory not found"l; exit 1; }
}

function gpuob {
    git push -u origin "$(git rev-parse --abbrev-ref HEAD)"
}

function gdcommits {
   git log --graph --pretty=format:'%C(bold)%h%Creset%C(magenta)%d%Creset %s %C(yellow)<%an> %C(cyan)(%cr)%Creset' --abbrev-commit --date=relative "$(git symbolic-ref --short HEAD)".."$1"
}

function gtrefresh() {
    for tag in `git tag` ; do
        git tag -d $tag;
    done
    git fetch --tags
}

# Create dir and go inside
function mdcd {
    { test mkdir "$1"; cd "$1"; } || { echo "Operation failed"; exit 1; }
}

# Move in place
function mvip {
    mv "$1" "$(realpath "$(dirname "$1")")/$2"
}

# Copy in place
function cpip {
    cp "$1" "$(realpath "$(dirname "$1")")/$2"
}

# Copy in place recursively
function cpipr {
    cp -r "$1" "$(realpath "$(dirname "$1")")/$2"
}

successmsg "Functions done. ${CHECK}"
