#!/bin/bash

export MC_DOTFILES_PATH="$HOME/.mcustiel"
CURDIR="$MC_DOTFILES_PATH/startup"

source "$CURDIR/msgfunctions"
source "$CURDIR/exports"
source "$CURDIR/functions"
source "$CURDIR/aliases"
source "$CURDIR/path"
source "$CURDIR/ssh-keys"
source "$CURDIR/tools"

importantmsg "Useful commands: "

infomsg " - mdcd [dirname]                     - Creates directory dirname and gets into it"
infomsg " - mip [dir]/[file_a] [file_b]        - Moves dir/file_a to dir/file_b"
infomsg " - cip [dir]/[file_a] [file_b]        - Copies dir/file_a to dir/file_b"
infomsg " - cipr [dir]/[file_a] [new-file_b]   - Copies dir/file_a to dir/file_b recursively"
echo

infomsg " - show <dirname>                     - Opens dirname in file explorer"
infomsg " - dev <dirname>                      - Opens dirname in IDE"
echo

infomsg " - tl                                 - List files as a tree"
infomsg " - dsrc                               - Stop all running docker containers"
echo

infomsg " - goto-*                             - Jump to projects folders directly"
echo

infomsg " - gccm <commit_type> <msg>           - Do a conventional commit"
infomsg " - gdcommits <branch>                 - Calculate difference of commits between current and <branch>"
echo 

fun
