#!/bin/bash

msg "Setting up paths..."

YARN_BIN_PATH=$HOME/.yarn/bin # $ yarn global bin
GLOBAL_SCRIPTS_PATH=$HOME/.mcustiel/global-scripts/

export PATH=${GLOBAL_SCRIPTS_PATH}:${YARN_BIN_PATH}:${PATH}

successmsg "Paths done. ${CHECK}"
