#!/bin/bash

# If ssh keys were not added yet, add all keys

msg "Registering SSH keys..."

PPKDIR=~/.ssh
EXT=".pub"

function add_key() {
    KEY=$1

    infomsg "Adding ${KEY} to ssh-agent."
    ssh-add "${KEY}"
    infomsg "${KEY} added."
}

for key in "$PPKDIR"/*"$EXT"; do
    # Add only private keys to ssh-agent
    PRIVATE_KEY=${key/$EXT/}
    KEY_CONTENT=$(cat "$key" | awk '{print $1,$2}')

    CONTENT_GREP_RESULT=$(ssh-add -L | grep "${KEY_CONTENT}")

    if [ ! -z "$CONTENT_GREP_RESULT" ]; then
        infomsg "${PRIVATE_KEY} was already added, skipping."
    else
        add_key "$PRIVATE_KEY"
    fi
done

successmsg "SSH Keys done. ${CHECK}"
